version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test:coverage
            - run: yarn build
            - store_artifacts:
                path: coverage
            - store_artifacts:
                path: public
            - codecov/upload:
                file: coverage/cobertura-coverage.xml
workflows:
  build-and-test:
    jobs:
      - build-and-test
